function meshToCSV(T,X,Y,name,folder)
%Function that receives the mesh generated by Delaunay and the coordinates 
%arrays, converts the mesh vertices to graph vertices and saves the 
%corresponding graph into two spreadsheets. One spreadsheet has the 
%vertices names and the other one has a dissimilarity matrix. The beginning
%of the spreadsheet names and the corresponding folder are passed as 
%additional parameters
%c Newton Spolaôr, Antonio Parmezan, Huei Diana Lee et al., 08/2019

%% geração da primeira planilha
vertices=unique((T(:)));
csvwrite(strcat(folder,'/',name,'_vertices.csv'),vertices);

%% geração da segunda planilha
nv=size(vertices,1);
dm = zeros(nv); %inicia matriz com zero em toda a célula. 
              %Futuramente, somente restará 0 nas células que cruzam
              %linha e coluna de vértices sem aresta entre eles

%preenche células quando houver aresta entre vértices
nl=size(T,1);
%edges=[];

for i=1:nl
    for j=1:2
        for k=j+1:3
            V1=[X(T(i,j)),Y(T(i,j))];
            V2=[X(T(i,k)),Y(T(i,k))];
            distance=norm(V1-V2);
            dm(T(i,j),T(i,k))=distance;
            dm(T(i,k),T(i,j))=distance;
        end
    end
   %edge=getEdges(T(i,:)) 
   %[edges;edge]
end
%csvwrite('edges.csv',unique(edges));

csvwrite(strcat(folder,'/',name,'_matrix.csv'),dm);